apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eh9igr6cp-go 
  janus-idp.io/tekton: eh9igr6cp-go
  backstage.io/kubernetes-id: eh9igr6cp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eh9igr6cp-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml