apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eh9igr6cp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eh9igr6cp-go 
  name: eh9igr6cp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eh9igr6cp-go 
